name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *"  # Atualiza a cada 5 horas
  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do repositório
      - uses: actions/checkout@v2

      # Gera os arquivos da cobrinha
      - uses: Platane/snk@v2.1.0  # Use uma versão específica
        id: snake-gif
        with:
          github_user_name: GustavoOrelio
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Verifica o status do git
      - run: git status

      # Faz o push das alterações
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0  # Use uma versão específica
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Publica os arquivos no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
