# GitHub Action for generating a contribution graph with a snake eating your contributions.

# ![snake gif](https://github.com/your-user-name/your-user-name/blob/output/github-contribution-grid-snake.gif)

name: Generate Snake

# Controls when the action will run.
on:
  schedule:
    - cron: "0 */12 * * *" # executa a cada 12 horas

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

  # Also run on every push on the master branch
  push:
    branches:
      - main

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Generate the snake files in './dist/'
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: GustavoOrelio
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: "blue"
          color_snake: "#00B8D4"
          color_dots: "#193549,#35495e,#41b883,#00B8D4"

      - name: Show build status
        run: git status

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
